language: node_js
sudo: required
node_js: 
  - 7.9.0

cache:
  directories:
    - node_modules

branches:
  only:
    - master 

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save
  - source travis_env_init.sh # 指定 shell 脚本文件来做初始化

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "${GIT_USER_NAME}"
  - git config user.email "${GIT_USER_EMAIL}"
  - sed -i "s/GIT_REPO_TOKEN/${GIT_REPO_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle