language: node_js # 指定语言环境
node_js:
  - "8" # 指定 NodeJS 版本
dist: trusty # 指定系统版本。trusty 是指 Ubuntu 14.04 发行版的名称
sudo: required # 是否需要 sudo 权限

branches: # 指定要构建的分支
  only: # only 表示只构建以下分支
  - master 

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "fangge889"
  - git config user.email "fangge889@gmail.com"
  - sed -i "s/gh_token/${GIT_REPO_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle

notifications: # 设置通知项
  email: true
