# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 7.9.0

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - master 
 
# Start: Build Lifecycle
install:
  - npm install -g gulp > /dev/null
  - npm install -g hexo-cli > /dev/null
  - npm install

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  - gulp

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "${GIT_USER_NAME}"
  - git config user.email "${GIT_USER_EMAIL}"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/GIT_REPO_TOKEN/${GIT_REPO_TOKEN}/g" ./_config.yml
  
after_success: # 在构建成功后要运行的命令，构建失败不会执行，其他同上
  - hexo deploy > /dev/null # 通过 hexo 的 deploy 命令部署博客

notifications: # 设置通知项
  email: true
# End: Build LifeCycle